USE CAR_DATABASE;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Audit_Log;
DROP TABLE IF EXISTS Invoice_Detail;
DROP TABLE IF EXISTS Payment;
DROP TABLE IF EXISTS Warranty;
DROP TABLE IF EXISTS Invoice;
DROP TABLE IF EXISTS Account;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Vehicle;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Employee;

SET FOREIGN_KEY_CHECKS = 1;
